### ISSUE TITLE
Bug with !fc and !uc with multiples classes

### ISSUE THREAD

**Issue by FrancoisDuchene** [Maxmawt/Discord-SINFO_Bot#1]
# Description
Sometimes when i *follow* or *unfollow* multiple classes, some of the action doesn't works in the end, the role is not properly set.
I did a series of experiments with certain inputs to detect the possible error. However until now, the bug seems to happen randomly.

# Measurements
All measurements below have been executed sequentially.
## Fields description
- ID : Number of experiment
- Item : Number of courses added/removed
- fc/uc : `!fc` for follow course, `!uc` for unfollow course
- Courses : Courses added after `!fc/uc` command
- Courses missing/still there : Define abnormal execution. When command is `!fc`, the courses listed here are courses that weren't correctly added. On the other hand, when the command is `!uc`, those are the courses not correctly removed.
## Data
|ID  |Item | fc/uc | Courses | Courses missing/still there|
|:---|:---:|:-----:|:-----:|-------------:|
| 1  |  1  |  fc   | LBIR1315 | \ |
| 2  |  2  |  fc   | LBIR1315 LINGI2142 | \ |
| 3  |  4  |  fc   | LBIR1315 LINGI2142 LINGI1123 LINGI1131 | LINGI2142 |
| 4  |  4  |  uc   | LBIR1315 LINGI2142 LINGI1123 LINGI1131 | LINGI1123 |
| 5  |  5  |  fc   | LBIR1315 LINGI2142 LINGI1123 LINGI1131 LECGE1317 | LINGI1131 |
| 6  |  5  |  uc   | LBIR1315 LINGI2142 LINGI1123 LINGI1131 LECGE1317 | LINGI2142 |
| 7  |  2  |  fc   | LBIR1315 LINGI2142 | LBIR1315 |
| 8  |  2  |  fc   | LBIR1315 LINGI2142 | \ |
| 9  |  2  |  uc   | LBIR1315 LINGI2142 | LBIR1315 |
| 10 |  2  |  uc   | LBIR1315 LINGI2142 | \ |
| 11 |  4  |  fc   | LINGI2142 LINGI1341 LINGI1123 LECGE1222 | LINGI2142 LINGI1123 |
| 12 |  4  |  uc   | LINGI2142 LINGI1341 LINGI1123 LECGE1222 | LINGI1341 |
| 13 |  4  |  uc   | LINGI2142 LINGI1341 LINGI1123 LECGE1222 | \ |
| 14 |  4  |  fc   | LINGI2142 LINGI1341 LINGI1123 LECGE1222 | \ |
| 15 |  4  |  uc   | LINGI2142 LINGI1341 LINGI1123 LECGE1222 | \ |
| 16 |  4  |  fc   | LINGI2142 LINGI1341 LINGI1123 LECGE1222 | \ |
| 17 |  4  |  uc   | LINGI2142 LINGI1341 LINGI1123 LECGE1222 | \ |
| 18 |  4  |  fc   | LINGI2142 LINGI1341 LINGI1123 LECGE1222 | LINGI1123 |
| 19 |  4  |  uc   | LINGI2142 LINGI1341 LINGI1123 LECGE1222 | \ |
| 20 |  4  |  fc   | LINGI2142 LINGI1341 LINGI1123 LECGE1222 | \ |
| 21 |  4  |  fc   | LINGI1341 LINGI2142 LINGI1123 LECGE1222 | \ |
| 22 |  4  |  uc   | LINGI1341 LINGI2142 LINGI1123 LECGE1222 | LINGI1341 LINGI1123 |
| 23 |  4  |  uc   | LINGI1341 LINGI2142 LINGI1123 LECGE1222 | \ |
| 24 |  4  |  fc   | LECGE1222 LINGI2142 LINGI1341 LINGI1123 | \ |
| 25 |  4  |  uc   | LECGE1222 LINGI2142 LINGI1341 LINGI1123 | \ |
| 26 |  4  |  fc   | LECGE1222 LINGI2142 LINGI1341 LINGI1123 | LECGE1222 LINGI1341 |
| 27 |  4  |  uc   | LECGE1222 LINGI2142 LINGI1341 LINGI1123 | \ |
| 28 |  4  |  fc   | LECGE1222 LINGI2142 LINGI1341 LINGI1123 | \ |
| 29 |  4  |  uc   | LECGE1222 LINGI2142 LINGI1341 LINGI1123 | LINGI1341 |
| 30 |  4  |  uc   | LECGE1222 LINGI2142 LINGI1341 LINGI1123 | \ |
| 31 |  4  |  fc   | LINGI1123 LINGI2142 LECGE1222 LINGI1341 | LINGI1123 |
| 32 |  4  |  uc   | LINGI1123 LINGI2142 LECGE1222 LINGI1341 | LECGE1222 |
| 33 |  4  |  uc   | LINGI1123 LINGI2142 LECGE1222 LINGI1341 | \ |

**Comment by Jimvy** [comment]
I'm impressed with the level of details :o

**Comment by FrancoisDuchene** [comment]
As the bug is pretty damn weird (and random), i wanted to be the most detailed possible

**Comment by icyrane** [comment]
Weird stuff, I don't have a single idea why this is failing. Gonna do some debugging via PyCharm and see what I can find

**Comment by icyrane** [comment]
Bonus observations:
!follow LBIR1315 LINGI2142 LINGI1123 LINGI1131
     - LINGI1123 missing
!follow LBIR1315 LINGI2142 LINGI1131 LINGI1123
     - LINGI1131 missing
!follow LINGI2142 LINGI1131 LBIR1315 LINGI1123
     - LINGI1131 missing

Seems to be consistent when doing it on my user

**Comment by icyrane** [comment]
Observations seem to vary depending on the user doing the command, the bug seems to come from `await client.add_roles(u, role)`
this line. Either wrong usage of the command or bug on discord.py's side
